In [2]:
from typing import List
from datetime import date
from sqlalchemy import String, Integer, ForeignKey, DECIMAL, Date
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy import create_engine, inspect, select
from sqlalchemy.orm import Session
from sqlalchemy import inspect
from sqlalchemy import text
import os
from pathlib import Path
import pandas as pd
from dotenv import load_dotenv
from adbc_driver_postgresql import dbapi
import pandas as pd
import os
import plotly.express as px
import plotly.io as pio
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.options.plotting.backend = 'plotly'
pio.templates.default = 'plotly_dark+presentation'

# --- Configuration ---
BASE_DIR = Path('./')
ENV_PATH = Path().cwd().parent/"creds.env"
load_dotenv(dotenv_path=ENV_PATH)

DB_USER = os.getenv("DB_USER", "postgres")
DB_PASS = os.getenv("DB_PASS")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_NAME = os.getenv("DB_NAME", "unarxive")

CONNECTION_STRING = f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}/{DB_NAME}"
engine = create_engine(CONNECTION_STRING)

In [10]:
print(DB_HOST)
print(DB_USER)
print(DB_PASS)
print(Path().cwd())

147.126.2.24
mgarciamelo
cotsEk-5padby-jivgib
/home/jupyter-mgarciamelo/ipynb

In [2]:
def run_query(query: str, engine=engine) -> pd.DataFrame:
  return pd.read_sql(query, engine)

In [3]:
sql = """
WITH top_cited AS (
    SELECT 
        citation_patent_id,
        COUNT(DISTINCT(patent_id)) AS citation_count
    FROM g_us_patent_citation
    GROUP BY citation_patent_id
    ORDER BY citation_count DESC
    LIMIT 20
)
SELECT *
FROM top_cited t
JOIN g_patent p ON t.citation_patent_id = p.patent_id
JOIN g_attorney_disambiguated a ON t.citation_patent_id = a.patent_id
JOIN g_assignee_disambiguated asg ON t.citation_patent_id = asg.patent_id
ORDER BY t.citation_count DESC
"""

display(pd.read_sql(text(sql), engine))

   citation_patent_id  citation_count patent_id patent_type patent_date                                       patent_title wipo_kind  num_claims  withdrawn                 filename patent_id  attorney_sequence                       attorney_id disambig_attorney_name_first disambig_attorney_name_last                     disambig_attorney_organization attorney_country patent_id  assignee_sequence                           assignee_id disambig_assignee_individual_name_first disambig_assignee_individual_name_last             disambig_assignee_organization  assignee_type                           location_id
0             4683202            5784   4683202     utility  1987-07-28      Process for amplifying nucleic acid sequences         A          21          0  pftaps19870728_wk30.zip   4683202                  1  574539b9c6e6fefa36bfb4a84f0588f4                    Albert P.                     Halluin                                                                       4683202                  0  be1a71b8-c282-44cf-ae7b-a82d30a93619                                    None                                   None                          Cetus Corporation            2.0  c7f663aa-16c7-11ed-9b5f-1234bde3cd05
1             4683202            5784   4683202     utility  1987-07-28      Process for amplifying nucleic acid sequences         A          21          0  pftaps19870728_wk30.zip   4683202                  0  55f611002a893a054ebd81aafbf10072                     Janet E.                       Hasak                                                                       4683202                  0  be1a71b8-c282-44cf-ae7b-a82d30a93619                                    None                                   None                          Cetus Corporation            2.0  c7f663aa-16c7-11ed-9b5f-1234bde3cd05
2             4683195            5238   4683195     utility  1987-07-28  Process for amplifying, detecting, and/or-clon...         A          26          0  pftaps19870728_wk30.zip   4683195                  0  55f611002a893a054ebd81aafbf10072                     Janet E.                       Hasak                                                                       4683195                  0  be1a71b8-c282-44cf-ae7b-a82d30a93619                                    None                                   None                          Cetus Corporation            2.0  c7f663aa-16c7-11ed-9b5f-1234bde3cd05
3             4683195            5238   4683195     utility  1987-07-28  Process for amplifying, detecting, and/or-clon...         A          26          0  pftaps19870728_wk30.zip   4683195                  1  574539b9c6e6fefa36bfb4a84f0588f4                    Albert P.                     Halluin                                                                       4683195                  0  be1a71b8-c282-44cf-ae7b-a82d30a93619                                    None                                   None                          Cetus Corporation            2.0  c7f663aa-16c7-11ed-9b5f-1234bde3cd05
4             5523520            4891   5523520     utility  1996-06-04                    Mutant dwarfism gene of petunia         A          20          0  pftaps19960604_wk23.zip   5523520                  0  849a92c42d1623421524dbc26fc44ea0                                                                                Rothwell, Figg, Ernst & Kurz                    5523520                  0  3be2dc91-4af7-4603-b9c9-e36b04464e8e                                    None                                   None                      Goldsmith Seeds, Inc.            2.0  15a22f0f-16c8-11ed-9b5f-1234bde3cd05
5             7674650            4307   7674650     utility  2010-03-09  Semiconductor device and manufacturing method ...        B2          28          0            ipg100309.xml   7674650                  0  d0ec2435db8a518d82eeb5cd905c6f39                                                                                              Cook Alex Ltd.                    7674650                  0  3cbd0e04-001d-46a5-986d-456478d9e140                                    None                                   None  Semiconductor Energy Laboratory Co., Ltd.            3.0  7159b2a8-16c8-11ed-9b5f-1234bde3cd05
6             7061014            4050   7061014     utility  2006-06-13  Natural-superlattice homologous single crystal...        B2          12          0            ipg060613.xml   7061014                  0  b2a3fc49e9820b0980302263ef914c24                                                                   Weterman, Hattori, Daniels & Adrian, LLP.                    7061014                  0  eb2ebb85-8503-414d-9730-aed37c7ab928                                    None                                   None        Japan Science and Technology Agency            3.0  a430f863-16c8-11ed-9b5f-1234bde3cd05
7             5731856            4035   5731856     utility  1998-03-24  Methods for forming liquid crystal displays in...         A          25          0  pftaps19980324_wk12.zip   5731856                  0  42891b44c6faa644f70ef9c230ff1be3                                                                              Myers, Bigel, Sibley & Sajovec                    5731856                  0  d1d96a91-c5e6-4090-ba39-4af2494eb35c                                    None                                   None              SAMSUNG ELECTRONICS CO., LTD.            3.0  3eea8bf8-16c8-11ed-9b5f-1234bde3cd05
8             7732819            4030   7732819     utility  2010-06-08  Semiconductor device and manufacturing method ...        B2          49          0            ipg100608.xml   7732819                  0  c6bde8e25976dd208350aad111ed92e8                                                                                     Husch Blackwell Sanders                    7732819                  0  3cbd0e04-001d-46a5-986d-456478d9e140                                    None                                   None  Semiconductor Energy Laboratory Co., Ltd.            3.0  7159b2a8-16c8-11ed-9b5f-1234bde3cd05
9             6727522            3992   6727522     utility  2004-04-27                Transistor and semiconductor device        B1          44          0             pg040427.zip   6727522                  0  60001a7c83725e6a3b883b37fbc5bcb5                                                                                        Neifeld IP Law, P.C.                    6727522                  0  7f546aca-e348-461a-8460-ca6146537efb                                    None                                   None               Japan Science and Technology            3.0  34b4468e-16c8-11ed-9b5f-1234bde3cd05
10            6294274            3992   6294274     utility  2001-09-25                                    Oxide thin film         A          20          0  pftaps20010925_wk39.zip   6294274                  0  1647b54ff2e4c4f20ec4067586cbf1dd                                                           Oblon, Spivak, McClelland, Maier & Neustadt, P.C.                    6294274                  0  8fdddeb9-5676-4575-814d-086bed885ec6                                    None                                   None                            TDK CORPORATION            3.0  42f90495-16c8-11ed-9b5f-1234bde3cd05
11            6294274            3992   6294274     utility  2001-09-25                                    Oxide thin film         A          20          0  pftaps20010925_wk39.zip   6294274                  0  1647b54ff2e4c4f20ec4067586cbf1dd                                                           Oblon, Spivak, McClelland, Maier & Neustadt, P.C.                    6294274                  1  1221d41a-495c-4771-843c-ddfcb7ad61b7                                 Hiroshi                                Kawazoe                                       None            NaN  1d2251c8-16c8-11ed-9b5f-1234bde3cd05
12            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  0  d6ca59f2f9b21329d51e713ebdfdc684                     David G.                      Conlin                                                                       6563174                  0  df6d5e3d-5ce0-4993-8350-d2aac669f1ef                                    None                                   None                     SHARP KABUSHIKI KAISHA            3.0  8d09bc30-16c8-11ed-9b5f-1234bde3cd05
13            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  2  9fbefefa2909bc13082cc148efb02e35                                                                                       Edwards & Angell, LLP               US   6563174                  2  c9b2c19d-a184-48ae-b020-d19a2c51dc58                                   Hideo                                   Ohno                                       None            5.0  a039f7b0-16c8-11ed-9b5f-1234bde3cd05
14            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  1  b35a4a4c2013145886d12bb9ef3f1c9f                      John B.                   Alexander                                                                       6563174                  2  c9b2c19d-a184-48ae-b020-d19a2c51dc58                                   Hideo                                   Ohno                                       None            5.0  a039f7b0-16c8-11ed-9b5f-1234bde3cd05
15            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  0  d6ca59f2f9b21329d51e713ebdfdc684                     David G.                      Conlin                                                                       6563174                  2  c9b2c19d-a184-48ae-b020-d19a2c51dc58                                   Hideo                                   Ohno                                       None            5.0  a039f7b0-16c8-11ed-9b5f-1234bde3cd05
16            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  2  9fbefefa2909bc13082cc148efb02e35                                                                                       Edwards & Angell, LLP               US   6563174                  0  df6d5e3d-5ce0-4993-8350-d2aac669f1ef                                    None                                   None                     SHARP KABUSHIKI KAISHA            3.0  8d09bc30-16c8-11ed-9b5f-1234bde3cd05
17            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  1  b35a4a4c2013145886d12bb9ef3f1c9f                      John B.                   Alexander                                                                       6563174                  0  df6d5e3d-5ce0-4993-8350-d2aac669f1ef                                    None                                   None                     SHARP KABUSHIKI KAISHA            3.0  8d09bc30-16c8-11ed-9b5f-1234bde3cd05
18            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  2  9fbefefa2909bc13082cc148efb02e35                                                                                       Edwards & Angell, LLP               US   6563174                  1  93be4d0e-a750-4537-82ff-0628400ff213                                 Masashi                               Kawasaki                                       None            5.0  a039f7b0-16c8-11ed-9b5f-1234bde3cd05
19            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  1  b35a4a4c2013145886d12bb9ef3f1c9f                      John B.                   Alexander                                                                       6563174                  1  93be4d0e-a750-4537-82ff-0628400ff213                                 Masashi                               Kawasaki                                       None            5.0  a039f7b0-16c8-11ed-9b5f-1234bde3cd05
20            6563174            3974   6563174     utility  2003-05-13     Thin film transistor and matrix display device        B2          24          0             pg030513.zip   6563174                  0  d6ca59f2f9b21329d51e713ebdfdc684                     David G.                      Conlin                                                                       6563174                  1  93be4d0e-a750-4537-82ff-0628400ff213                                 Masashi                               Kawasaki                                       None            5.0  a039f7b0-16c8-11ed-9b5f-1234bde3cd05
21            7064346            3961   7064346     utility  2006-06-20                Transistor and semiconductor device        B2          24          0            ipg060620.xml   7064346                  0  68230aa228b17c4da3006f7a6835f50e                                                                                          Niefeld IP Law, PC                    7064346                  0  eb2ebb85-8503-414d-9730-aed37c7ab928                                    None                                   None        Japan Science and Technology Agency            3.0  34b4468e-16c8-11ed-9b5f-1234bde3cd05
22            7402506            3947   7402506     utility  2008-07-22  Methods of making thin film transistors compri...        B2          43          0            ipg080722.xml   7402506                  0  06f5e3e5b0802c5c77516c68a8dc1bb3                     Chris P.                      Konkol                                                                  US   7402506                  0  138a9855-d77a-45ec-ac01-01da9d939bb6                                    None                                   None                      EASTMAN KODAK COMPANY            2.0  d929a955-16c7-11ed-9b5f-1234bde3cd05
23            7323356            3946   7323356     utility  2008-01-29  LnCuO(S,Se,Te)monocrystalline thin film, its m...        B2          10          0            ipg080129.xml   7323356                  0  29e14a153693f14b2cfc6c3cc75812d5                                                                  Westerman, Hattori, Daniels & Adrian, LLP.                    7323356                  0  eb2ebb85-8503-414d-9730-aed37c7ab928                                    None                                   None        Japan Science and Technology Agency            3.0  a430f863-16c8-11ed-9b5f-1234bde3cd05
24            7411209            3943   7411209     utility  2008-08-12  Field-effect transistor and method for manufac...        B2          14          0            ipg080812.xml   7411209                  0  edb551ae21fae89c9ff514dcb00f8a3a                                                                         Fitzpatrick, Cella, Harper & Scinto                    7411209                  0  61d52265-4aea-4f20-b743-c4a9faef6860                                    None                                   None                     Canon Kabushiki Kaisha            3.0  42f90495-16c8-11ed-9b5f-1234bde3cd05
25            7453087            3929   7453087     utility  2008-11-18  Thin-film transistor and thin-film diode havin...        B2          15          0            ipg081118.xml   7453087                  0  edb551ae21fae89c9ff514dcb00f8a3a                                                                         Fitzpatrick, Cella, Harper & Scinto                    7453087                  0  61d52265-4aea-4f20-b743-c4a9faef6860                                    None                                   None                     Canon Kabushiki Kaisha            3.0  42f90495-16c8-11ed-9b5f-1234bde3cd05

In [ ]:
sql = """
WITH top_cited AS (
    SELECT 
        citation_patent_id,
        COUNT(DISTINCT(patent_id)) AS citation_count
    FROM g_us_patent_citation
    GROUP BY citation_patent_id
    ORDER BY citation_count DESC
    LIMIT 20
)
SELECT *
FROM top_cited t
JOIN g_patent p ON t.citation_patent_id = p.patent_id
JOIN g_cpc_current c ON t.citation_patent_id = c.patent_id
ORDER BY t.citation_count DESC
"""
display(pd.read_sql(text(sql), engine))

In [5]:
sql = """
WITH top_cited AS (
    SELECT citation_patent_id,
           COUNT(DISTINCT patent_id) AS citation_count
    FROM g_us_patent_citation c
    JOIN g_patent p ON c.citation_patent_id = p.patent_id
    WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
    GROUP BY citation_patent_id
    ORDER BY citation_count DESC
    LIMIT 5
)
SELECT *
FROM top_cited t
JOIN g_patent p ON t.citation_patent_id = p.patent_id
JOIN g_cpc_current c ON t.citation_patent_id = c.patent_id
WHERE c.cpc_sequence = 0
ORDER BY t.citation_count DESC;
"""

df = pd.read_sql(text(sql), engine)
display(df)

ProgrammingError: (psycopg2.errors.AmbiguousColumn) column reference "patent_id" is ambiguous
LINE 4:            COUNT(DISTINCT patent_id) AS citation_count
                                  ^

[SQL:
WITH top_cited AS (
    SELECT citation_patent_id,
           COUNT(DISTINCT patent_id) AS citation_count
    FROM g_us_patent_citation c
    JOIN g_patent p ON c.citation_patent_id = p.patent_id
    WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
    GROUP BY citation_patent_id
    ORDER BY citation_count DESC
    LIMIT 5
)
SELECT *
FROM top_cited t
JOIN g_patent p ON t.citation_patent_id = p.patent_id
JOIN g_cpc_current c ON t.citation_patent_id = c.patent_id
WHERE c.cpc_sequence = 0
ORDER BY t.citation_count DESC;
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [7]:
sql = '''
SELECT loc.disambig_state, 
       COUNT(DISTINCT CONCAT(c.patent_id, '-', c.citation_patent_id)) AS citation_count
FROM g_us_patent_citation c
JOIN g_patent p ON c.citation_patent_id = p.patent_id
JOIN g_inventor_disambiguated inv ON p.patent_id = inv.patent_id
JOIN g_location_disambiguated loc ON inv.location_id = loc.location_id
WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
  AND loc.disambig_country = 'US'
  AND loc.disambig_state IS NOT NULL
GROUP BY loc.disambig_state
ORDER BY citation_count DESC
LIMIT 50;
'''
df = pd.read_sql(text(sql), engine)
display(df)

   disambig_state  citation_count
0              CA        11736523
1              OH         3012989
2              MA         2417866
3              NY         2330397
4              TX         2102936
5              WA         1945780
6              CT         1839070
7              NJ         1531188
8              MI         1428757
9              PA         1376923
10             IL         1326087
11             MN         1306362
12             FL         1268406
13             CO         1054427
14             OR          913674
15             NC          911480
16             AZ          778903
17             GA          738235
18             WI          701812
19             VA          667215
20             MD          600467
21             IN          558020
22             NH          421103
23             UT          414972
24             MO          348631
25             TN          344869
26             KY          330523
27             NV          313439
28             KS          224403
29             IA          206624
30             SC          203141
31             ID          194322
32             RI          164313
33             OK          154991
34             NM          121819
35             VT          120784
36             AL          109018
37             DE          108074
38             ME           99120
39             LA           89491
40             DC           85101
41             NE           80495
42             HI           58799
43             MT           56044
44             MS           51855
45             AR           51280
46             WY           37010
47             MH           31903
48             WV           31429
49             ND           30461

In [3]:
sql = """
SELECT EXTRACT(YEAR FROM p.patent_date) AS year,
    COUNT(DISTINCT CONCAT(c.patent_id, '-', c.citation_patent_id)) AS citation_count
FROM g_us_patent_citation c
JOIN g_patent p ON c.citation_patent_id = p.patent_id
WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
GROUP BY year
ORDER BY citation_count DESC;
"""
pd.read_sql(text(sql), engine)

      year  citation_count
0   2006.0         4186766
1   2010.0         3832887
2   2012.0         3553211
3   2013.0         3551660
4   2005.0         3521116
5   2007.0         3507857
6   2011.0         3482871
7   2014.0         3368211
8   2008.0         3206258
9   2009.0         3104452
10  2015.0         2934038
11  2016.0         2711635
12  2017.0         2567849
13  2018.0         2014463
14  2019.0         1957565
15  2020.0         1427606
16  2021.0          991528
17  2022.0          629936
18  2023.0          367326
19  2024.0          188977
20  2025.0           21220

In [4]:
sql = """
SELECT cpc_class, COUNT(DISTINCT CONCAT(c.patent_id, '-', c.citation_patent_id)) AS citation_count
FROM g_us_patent_citation c
JOIN g_patent p ON c.citation_patent_id = p.patent_id
JOIN g_cpc_current cpc ON p.patent_id = cpc.patent_id
WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
GROUP BY cpc_class
ORDER BY citation_count DESC
LIMIT 20;
"""
pd.read_sql(text(sql), engine)

   cpc_class  citation_count
0        A61        12208715
1        G06         9180074
2        H04         7666218
3        Y10         4438450
4        H01         3629082
5        G01         2881646
6        Y02         2724062
7        H10         1732216
8        G02         1341204
9        B60         1318625
10       H02         1229010
11       G11         1125313
12       C07         1098083
13       G16          970553
14       F16          917130
15       H05          896479
16       G07          883762
17       C12          867396
18       G05          862533
19       A63          806198

In [12]:
sql = """
SELECT *
FROM g_cpc_current cpc
WHERE cpc.patent_id = '10000271';
"""

pd.read_sql(text(sql), engine)

  patent_id  cpc_sequence cpc_section cpc_class cpc_subclass   cpc_group     cpc_type
0  10000271             0           B       B64         B64C  B64C1/1461  inventional
1  10000271             1           B       B64         B64C  B64C1/1423  inventional
2  10000271             2           E       E06         E06B    E06B7/23  inventional
3  10000271             3           B       B60         B60J  B60J10/244   additional

In [4]:
sql = """
SELECT *
FROM g_location_disambiguated l
JOIN g_inventor_disambiguated i ON l.location_id = i.location_id
JOIN g_patent p ON i.patent_id = p.patent_id
WHERE p.patent_id = '7674650';
"""

pd.read_sql(text(sql), engine)

                            location_id disambig_city disambig_state disambig_country   latitude   longitude county state_fips county_fips patent_id  inventor_sequence         inventor_id disambig_inventor_name_first disambig_inventor_name_last gender_code                           location_id patent_id patent_type patent_date                                       patent_title wipo_kind  num_claims  withdrawn       filename
0  1d2251c8-16c8-11ed-9b5f-1234bde3cd05      Yokohama           None               JP  35.444991  139.636768   None       None        None   7674650                  0  fl:ke_ln:akimoto-8                        Kengo                     Akimoto           M  1d2251c8-16c8-11ed-9b5f-1234bde3cd05   7674650     utility  2010-03-09  Semiconductor device and manufacturing method ...        B2          28          0  ipg100309.xml
1  1d2251c8-16c8-11ed-9b5f-1234bde3cd05      Yokohama           None               JP  35.444991  139.636768   None       None        None   7674650                  2     fl:no_ln:sone-5                     Norihito                        Sone           M  1d2251c8-16c8-11ed-9b5f-1234bde3cd05   7674650     utility  2010-03-09  Semiconductor device and manufacturing method ...        B2          28          0  ipg100309.xml
2  1d2251c8-16c8-11ed-9b5f-1234bde3cd05      Yokohama           None               JP  35.444991  139.636768   None       None        None   7674650                  1   fl:ta_ln:honda-37                      Tatsuya                       Honda           M  1d2251c8-16c8-11ed-9b5f-1234bde3cd05   7674650     utility  2010-03-09  Semiconductor device and manufacturing method ...        B2          28          0  ipg100309.xml

In [10]:
sql = """
SELECT cpc_class, cpc_class_title, COUNT(*) as subclasses
FROM g_cpc_title
GROUP BY cpc_class, cpc_class_title
ORDER BY subclasses DESC
LIMIT 10;
"""

pd.read_sql(text(sql), engine)

  cpc_class                                    cpc_class_title  subclasses
0       H01                                  ELECTRIC ELEMENTS       20504
1       Y10          TECHNICAL SUBJECTS COVERED BY FORMER USPC       16049
2       A61             MEDICAL OR VETERINARY SCIENCE; HYGIENE       13709
3       C12  BIOCHEMISTRY; BEER; SPIRITS; WINE; VINEGAR; MI...       10479
4       H04                   ELECTRIC COMMUNICATION TECHNIQUE       10321
5       G01                                 MEASURING; TESTING       10053
6       G05                            CONTROLLING; REGULATING        9318
7       B65  CONVEYING; PACKING; STORING; HANDLING THIN OR ...        9019
8       B01  PHYSICAL OR CHEMICAL PROCESSES OR APPARATUS IN...        8475
9       B60                                VEHICLES IN GENERAL        8389

In [9]:
sql = '''
SELECT COUNT(DISTINCT patent_id)
FROM g_patent p
WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
'''

pd.read_sql(text(sql), engine)

     count
0  6188004

In [7]:
sql = '''
SELECT COUNT(c.patent_id)
FROM g_us_patent_citation c
JOIN g_patent p ON c.patent_id = p.patent_id
WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
'''

pd.read_sql(text(sql), engine)

       count
0  122082531

In [8]:
sql = '''
SELECT AVG(cite_count)
FROM (
    SELECT c.citation_patent_id, COUNT(*) AS cite_count
    FROM g_us_patent_citation c
    JOIN g_patent p ON c.citation_patent_id = p.patent_id
    WHERE EXTRACT(YEAR FROM p.patent_date) > 2004
    GROUP BY c.citation_patent_id
) sub

'''
pd.read_sql(text(sql), engine)

         avg
0  13.827994

In [9]:
sql  = '''
SELECT *
FROM g_us_patent_citation c
JOIN g_patent p ON c.patent_id = p.patent_id
JOIN g_assignee_disambiguated a ON p.patent_id = a.patent_id
WHERE disambig_assignee_organization LIKE '%Apple%'
AND EXTRACT(YEAR FROM p.patent_date) = 2006
LIMIT 100;
'''
pd.read_sql(text(sql), engine)

   patent_id  citation_sequence citation_patent_id citation_date        record_name  citation_category patent_id patent_type patent_date                                       patent_title wipo_kind  num_claims  withdrawn       filename patent_id  assignee_sequence                           assignee_id disambig_assignee_individual_name_first disambig_assignee_individual_name_last disambig_assignee_organization  assignee_type                           location_id
0    7083974                  0            5333675    1994-08-01      Mullis et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
1    7083974                  1            5475610    1995-12-01      Atwood et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
2    7083974                  2            5656493    1997-08-01      Mullis et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
3    7083974                  3            5693233    1997-12-01           Schembri     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
4    7083974                  4            5928907    1999-07-01  Woudenberg et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
5    7083974                  5            6015674    2000-01-01  Woudenberg et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
6    7083974                  6            6174670    2001-01-01     Wittwer et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
7    7083974                  7            6303305    2001-10-01     Wittwer et al.     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
8    7083974                  8            6387621    2002-05-01            Wittwer     cited by other   7083974     utility  2006-08-01  Rotatable sample disk and method of loading a ...        B2          19          0  ipg060801.xml   7083974                  0  03d6786b-977a-483d-b3cd-3bf377f4174c                                    None                                   None            Applera Corporation            2.0  1416e13d-16c8-11ed-9b5f-1234bde3cd05
9    D519731                  0            D171247    1954-01-01           Charnota     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
10   D519731                  1            D306654    1990-03-01              Brown     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
11   D519731                  2            D345646    1994-04-01              Knapp     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
12   D519731                  3            D348981    1994-07-01        Dill et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
13   D519731                  4            D354677    1995-01-01             Troyer     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
14   D519731                  5            D370559    1996-06-01              Arndt     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
15   D519731                  6            D373241    1996-09-01      Chavez et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
16   D519731                  7            D375197    1996-11-01            Laherty     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
17   D519731                  8            D392097    1998-03-01     Pottala et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
18   D519731                  9            D393744    1998-04-01       Wandt et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
19   D519731                 10            D418119    1999-12-01             Rowell     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
20   D519731                 11            D426701    2000-06-01     Edwards et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
21   D519731                 12            D431250    2000-09-01            Richter     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
22   D519731                 13            D434898    2000-12-01     Jokinen et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
23   D519731                 14            D457309    2002-05-01             Tanaka  cited by examiner   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
24   D519731                 15            D465646    2002-11-01        Hendrickson     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
25   D519731                 16            D466287    2002-12-01             Tanaka     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
26   D519731                 17            D468525    2003-01-01       Boyle et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
27   D519731                 18            D475850    2003-06-01       Andre et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
28   D519731                 19            D476149    2003-06-01       Andre et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
29   D519731                 20            D478418    2003-08-01     Badillo et al.  cited by examiner   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
30   D519731                 21            D485060    2004-01-01            DeCotis     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
31   D519731                 22            D495871    2004-09-01     Moffitt et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
32   D519731                 23            D501309    2005-02-01             Sterns  cited by examiner   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
33   D519731                 24            D502313    2005-03-01      Lodato et al.  cited by examiner   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
34   D519731                 25            D503532    2005-04-01       Andre et al.     cited by other   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
35   D519731                 26            D508313    2005-08-01      Cullen et al.  cited by examiner   D519731      design  2006-05-02                           Electronic device holder        S1           1          0  ipg060502.xml   D519731                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
36   7099467                  0            5490653    1996-02-01          Ingwersen     cited by other   7099467     utility  2006-08-29                           Electronic device holder        B1          14          0  ipg060829.xml   7099467                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
37   7099467                  1            5745565    1998-04-01          Wakefield  cited by examiner   7099467     utility  2006-08-29                           Electronic device holder        B1          14          0  ipg060829.xml   7099467                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
38   7099467                  2            6084963    2000-07-01       Hirai et al.  cited by examiner   7099467     utility  2006-08-29                           Electronic device holder        B1          14          0  ipg060829.xml   7099467                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
39   7099467                  3            6189755    2001-02-01          Wakefield  cited by examiner   7099467     utility  2006-08-29                           Electronic device holder        B1          14          0  ipg060829.xml   7099467                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
40   7099467                  4            6246766    2001-06-01              Walsh     cited by other   7099467     utility  2006-08-29                           Electronic device holder        B1          14          0  ipg060829.xml   7099467                  0  4c8f5d40-1e37-48b9-8de1-56482301c08b                                    None                                   None            Apple Computer Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05