In [1]:
from typing import List
from datetime import date
from sqlalchemy import String, Integer, ForeignKey, DECIMAL, Date
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy import create_engine, inspect, select
from sqlalchemy.orm import Session
from sqlalchemy import inspect
from sqlalchemy import text
import os
from pathlib import Path
import pandas as pd
from dotenv import load_dotenv
from adbc_driver_postgresql import dbapi
import pandas as pd
import os
import plotly.express as px
import plotly.io as pio
import pandas as pd

os.chdir("/home/jupyter-mgarciamelo/ipynb")

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.options.plotting.backend = 'plotly'
pio.templates.default = 'plotly_dark+presentation'

# --- Configuration ---
BASE_DIR = Path('./')
ENV_PATH = Path().cwd().parent/"creds.env"
load_dotenv(dotenv_path=ENV_PATH)

DB_USER = os.getenv("DB_USER", "postgres")
DB_PASS = os.getenv("DB_PASS")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_NAME = os.getenv("DB_NAME", "unarxive")

CONNECTION_STRING = f"postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}/{DB_NAME}"
engine = create_engine(CONNECTION_STRING)

147.126.2.24
mgarciamelo
cotsEk-5padby-jivgib
/home/jupyter-mgarciamelo/ipynb

In [3]:
def run_query(query: str, engine=engine) -> pd.DataFrame:
  return pd.read_sql(query, engine)

In [4]:
sql  = '''
SELECT *
FROM g_us_patent_citation c
JOIN g_patent p ON c.patent_id = p.patent_id
JOIN g_assignee_disambiguated a ON p.patent_id = a.patent_id
WHERE disambig_assignee_organization LIKE '%Apple%'
LIMIT 10;
'''
pd.read_sql(text(sql), engine)

  patent_id  citation_sequence citation_patent_id citation_date     record_name   citation_category patent_id patent_type patent_date                                       patent_title wipo_kind  num_claims  withdrawn       filename patent_id  assignee_sequence                           assignee_id disambig_assignee_individual_name_first disambig_assignee_individual_name_last disambig_assignee_organization  assignee_type                           location_id
0  11877157                  0            2013027    1935-09-01          Branch  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
1  11877157                  1            8353448    2013-01-01   Miller et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
2  11877157                  2            8381969    2013-02-01   Miller et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
3  11877157                  3            8466875    2013-06-01   Nakada et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
4  11877157                  4            8827153    2014-09-01  Rhoades et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
5  11877157                  5            8850196    2014-09-01   Blanco et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
6  11877157                  6            8943187    2015-01-01          Saylor  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
7  11877157                  7            9147117    2015-09-01    Madhu et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
8  11877157                  8            9348492    2016-05-01  Penilia et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
9  11877157                  9            9485251    2016-11-01    White et al.  cited by applicant  11877157     utility  2024-01-16  Checkpoint identity verification using mobile ...        B2          24          1  ipg240116.xml  11877157                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05

In [9]:
sql = '''
SELECT *
FROM g_patent p
JOIN g_assignee_disambiguated a ON p.patent_id = a.patent_id
WHERE p.patent_id = '7663607';
'''

pd.read_sql(text(sql), engine)

  patent_id patent_type patent_date            patent_title wipo_kind  num_claims  withdrawn       filename patent_id  assignee_sequence                           assignee_id disambig_assignee_individual_name_first disambig_assignee_individual_name_last disambig_assignee_organization  assignee_type                           location_id
0   7663607     utility  2010-02-16  Multipoint touchscreen        B2          11          0  ipg100216.xml   7663607                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                     Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05

In [6]:
sql  = '''
SELECT *
FROM g_us_patent_citation c
JOIN g_patent p ON c.patent_id = p.patent_id
JOIN g_assignee_disambiguated a ON p.patent_id = a.patent_id
WHERE c.citation_patent_id = '7663607' 
LIMIT 100;
'''
pd.read_sql(text(sql), engine)

   patent_id  citation_sequence citation_patent_id citation_date         record_name   citation_category patent_id patent_type patent_date                                       patent_title wipo_kind  num_claims  withdrawn          filename patent_id  assignee_sequence                           assignee_id disambig_assignee_individual_name_first disambig_assignee_individual_name_last       disambig_assignee_organization  assignee_type                           location_id
0   12293147                 15            7663607    2010-02-01    Hotelling et al.  cited by applicant  12293147     utility  2025-05-06  Device, method, and graphical user interface f...        B2          42          0     ipg250506.xml  12293147                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
1   10474108                 11            7663607    2010-02-01    Hotelling et al.  cited by applicant  10474108     utility  2019-11-12           Magnetic sensor array for crown rotation        B2          19          0     ipg191112.xml  10474108                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
2   10620781                158            7663607    2010-02-01    Hotelling et al.  cited by applicant  10620781     utility  2020-04-14  Device, method, and graphical user interface f...        B2          27          0     ipg200414.xml  10620781                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
3    8866767                  5            7663607    2010-02-01           Hotelling  cited by applicant   8866767     utility  2014-10-21                    Active stylus with high voltage        B2          20          0     ipg141021.xml   8866767                  0  abb6c599-9729-4194-8ab2-a57be403491c                                    None                                   None                    Atmel Corporation            2.0  13f05eea-16c8-11ed-9b5f-1234bde3cd05
4   10191576                409            7663607    2010-02-01    Hotelling et al.  cited by applicant  10191576     utility  2019-01-29                Touch screen liquid crystal display        B2          20          0     ipg190129.xml  10191576                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
5   11043055                 50            7663607    2010-02-01    Hotelling et al.  cited by applicant  11043055     utility  2021-06-22               Door lock system with contact sensor        B2          16          0     ipg210622.xml  11043055                  0  870d77e1-9cf9-498e-97fe-2e99d85cd5f9                                    None                                   None                    August Home, Inc.            2.0  4affd925-16c8-11ed-9b5f-1234bde3cd05
6    8970552                 15            7663607    2010-02-01    Hotelling et al.  cited by applicant   8970552     utility  2015-03-03           Method and device for position detection        B2          19          0     ipg150303.xml   8970552                  0  15db08b4-7ded-4ce8-8cd8-fbcf48fd8450                                    None                                   None         EGALAX_EMPIA TECHNOLOGY INC.            3.0  b5c9a039-16c7-11ed-9b5f-1234bde3cd05
7    9098242                 16            7663607    2010-02-01    Hotelling et al.  cited by applicant   9098242     utility  2015-08-04  Electronic devices with cover layers mounted t...        B2          14          0     ipg150804.xml   9098242                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
8    9939322                 14            7663607    2010-02-01    Hotelling et al.  cited by applicant   9939322     utility  2018-04-10  Polarization selective, frequency selective, a...        B2          20          0     ipg180410.xml   9939322                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
9   10191636                  7            7663607    2010-02-01  Hatelling S et al.  cited by applicant  10191636     utility  2019-01-29  Gesture mapping for image filter input parameters        B2          20          0     ipg190129.xml  10191636                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
10  11221697                 12            7663607    2010-02-01    Hotelling et al.  cited by applicant  11221697     utility  2022-01-11  Capacitive touch panel for sensing mechanical ...        B2           6          0     ipg220111.xml  11221697                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
11   9489125                  7            7663607    2010-02-01    Hotelling et al.   cited by examiner   9489125     utility  2016-11-08  Touch processing method and system using a GUI...        B2          19          0     ipg161108.xml   9489125                  0  3e7eb93f-6981-4486-88cd-e33ee9f284bb                                    None                                   None              RICH IP TECHNOLOGY INC.            3.0  b5c9a039-16c7-11ed-9b5f-1234bde3cd05
12  10042491                 21            7663607    2010-02-01    Hotelling et al.  cited by applicant  10042491     utility  2018-08-07  Cover accessory device for a portable electron...        B2          20          0     ipg180807.xml  10042491                  0  4d85fef9-f679-4f10-9073-47fea0631195                                    None                                   None           QuickStep Technologies LLC            2.0  047210f8-16c8-11ed-9b5f-1234bde3cd05
13  10289199                 23            7663607    2010-02-01    Hotelling et al.  cited by applicant  10289199     utility  2019-05-14                             Haptic feedback system        B2          26          0     ipg190514.xml  10289199                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
14  10585493                 32            7663607    2010-02-01    Hotelling et al.  cited by applicant  10585493     utility  2020-03-10                Touch sensitive mechanical keyboard        B2          19          0     ipg200310.xml  10585493                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
15  10585502                 13            7663607    2010-02-01    Hotelling et al.  cited by applicant  10585502     utility  2020-03-10          Touch sensor excitation using transformer        B2          20          0     ipg200310.xml  10585502                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
16  11966560                 46            7663607    2010-02-01    Hotelling et al.  cited by applicant  11966560     utility  2024-04-23  User interfaces for browsing content from mult...        B2          69          0     ipg240423.xml  11966560                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
17  12079420                 22            7663607    2010-02-01    Hotelling et al.  cited by applicant  12079420     utility  2024-09-03              Power management for touch controller        B2          20          0     ipg240903.xml  12079420                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
18   9462856                 36            7663607    2010-02-01    Hotelling et al.  cited by applicant   9462856     utility  2016-10-11  Wearable device with magnets sealed in a weara...        B2          21          0     ipg161011.xml   9462856                  0  80784090-98fe-41e7-94d3-6af562b2938e                                    None                                   None                           Hello Inc.            2.0  4affd925-16c8-11ed-9b5f-1234bde3cd05
19   RE46317                182            7663607    2010-02-01    Hotelling et al.  cited by applicant   RE46317     reissue  2017-02-21        Normalizing capacitive sensor array signals        E1          19          0     ipg170221.xml   RE46317                  0  c7454f98-6c18-4c00-b3b5-51cf36c0f55c                                    None                                   None               Monterey Research, LLC            2.0  c1ee6332-16c7-11ed-9b5f-1234bde3cd05
20  10054720                 19            7663607    2010-02-01    Hotelling et al.  cited by applicant  10054720     utility  2018-08-21                         Fresnel lens barrier rings        B2          16          0     ipg180821.xml  10054720                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
21  11562638                 46            7663607    2010-02-01    Hotelling et al.  cited by applicant  11562638     utility  2023-01-24  Electronic system and method for improving hum...        B2          20          0  ipg230124_r1.xml  11562638                  0  5e127032-26e3-465b-9a93-344c46176927                                    None                                   None                 Logitech Europe S.A.            3.0  6b3fdc33-16c8-11ed-9b5f-1234bde3cd05
22   8884926                126            7663607    2010-02-01    Hotelling et al.  cited by applicant   8884926     utility  2014-11-11          Light-based finger gesture user interface        B1          11          0     ipg141111.xml   8884926                  0  008c7fe3-92fc-4cde-9c25-6808723f800e                                    None                                   None                         Neonode Inc.            2.0  c1ee6332-16c7-11ed-9b5f-1234bde3cd05
23   RE49044                 28            7663607    2010-02-01    Hotelling et al.  cited by applicant   RE49044     reissue  2022-04-19                          Automatic avatar creation        E1          33          0     ipg220419.xml   RE49044                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
24   9081453                 68            7663607    2010-02-01    Hotelling et al.  cited by applicant   9081453     utility  2015-07-14            Single layer capacitive imaging sensors        B2          17          0     ipg150714.xml   9081453                  0  69eb26e4-c09c-4136-85e4-89bddddabe57                                    None                                   None               Synaptics Incorporated            2.0  13f05eea-16c8-11ed-9b5f-1234bde3cd05
25   9195353                  1            7663607    2010-02-01    Hotelling et al.  cited by applicant   9195353     utility  2015-11-24  Touch controllers, methods thereof, and device...        B2          22          0     ipg151124.xml   9195353                  0  d1d96a91-c5e6-4090-ba39-4af2494eb35c                                    None                                   None        SAMSUNG ELECTRONICS CO., LTD.            3.0  75436e0d-16c8-11ed-9b5f-1234bde3cd05
26  10303319                  0            7663607    2010-02-01    Hotelling et al.  cited by applicant  10303319     utility  2019-05-28           Pattern of Electrodes for a touch sensor        B2          20          0     ipg190528.xml  10303319                  0  452db239-6cab-47cc-b35b-55e6775e4f5c                                    None                                   None                      Neodrón Limited            3.0  6aa02d92-16c8-11ed-9b5f-1234bde3cd05
27  10795541               1704            7663607    2010-02-01    Hotelling et al.  cited by applicant  10795541     utility  2020-10-06            Intelligent organization of tasks items        B2          33          0     ipg201006.xml  10795541                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
28   8235460                  9            7663607    2010-02-01    Hotelling et al.      cited by other   8235460     utility  2012-08-07                            Vehicle window assembly        B2          20          0     ipg120807.xml   8235460                  0  a33b69e6-22a2-4b43-8c91-65ac87994d4d                                    None                                   None           NISSAN NORTH AMERICA, INC.            2.0  eb6cb467-16c7-11ed-9b5f-1234bde3cd05
29   9007342                 26            7663607    2010-02-01    Hotelling et al.  cited by applicant   9007342     utility  2015-04-14     Dynamic mode switching for fast touch response        B2          18          0     ipg150414.xml   9007342                  0  a0f6a28a-bed5-4a42-93d2-10ce78cb0ec2                                    None                                   None    Cypress Semiconductor Corporation            2.0  13f05eea-16c8-11ed-9b5f-1234bde3cd05
30   9557846                192            7663607    2010-02-01    Hotelling et al.  cited by applicant   9557846     utility  2017-01-31  Pressure-sensing touch system utilizing optica...        B2          17          0     ipg170131.xml   9557846                  0  2ef1cc38-6029-4e1c-8610-45bbae03a8f1                                    None                                   None                 CORNING INCORPORATED            2.0  fe1df660-16c7-11ed-9b5f-1234bde3cd05
31  10978090               1458            7663607    2010-02-01    Hotelling et al.  cited by applicant  10978090     utility  2021-04-13              Voice trigger for a digital assistant        B2          51          0     ipg210413.xml  10978090                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
32  11816916                  1            7663607    2010-02-01    Hotelling et al.  cited by applicant  11816916     utility  2023-11-14                                  Electronic device        B2          21          0     ipg231114.xml  11816916                  0  d1d96a91-c5e6-4090-ba39-4af2494eb35c                                    None                                   None        SAMSUNG ELECTRONICS CO., LTD.            3.0  755a6338-16c8-11ed-9b5f-1234bde3cd05
33   8716932                 23            7663607    2010-02-01    Hotelling et al.  cited by applicant   8716932     utility  2014-05-06                    Displays with minimized borders        B2          17          0     ipg140506.xml   8716932                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
34   9760192                352            7663607    2010-02-01    Hotelling et al.  cited by applicant   9760192     utility  2017-09-12                                      Touch sensing        B2          19          0     ipg170912.xml   9760192                  0  a0f6a28a-bed5-4a42-93d2-10ce78cb0ec2                                    None                                   None    Cypress Semiconductor Corporation            2.0  13f05eea-16c8-11ed-9b5f-1234bde3cd05
35   9866660                 25            7663607    2010-02-01    Hotelling et al.  cited by applicant   9866660     utility  2018-01-09           Electronic devices with concave displays        B2          22          0     ipg180109.xml   9866660                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
36  10928180                  4            7663607    2010-02-01           Hotelling   cited by examiner  10928180     utility  2021-02-23                        Flexible deformation sensor        B2          10          0     ipg210223.xml  10928180                  0  07c67629-63d5-4a7f-946e-b0ef2d762a8e                                    None                                   None                     Tactual Labs Co.            2.0  92237ca2-16c8-11ed-9b5f-1234bde3cd05
37   8941014                  0            7663607    2010-02-01           Hotelling  cited by applicant   8941014     utility  2015-01-27      Complex adhesive boundaries for touch sensors        B2          19          0     ipg150127.xml   8941014                  0  abb6c599-9729-4194-8ab2-a57be403491c                                    None                                   None                    Atmel Corporation            2.0  13f05eea-16c8-11ed-9b5f-1234bde3cd05
38   9361012                 23            7663607    2010-02-01    Hotelling et al.  cited by applicant   9361012     utility  2016-06-07                               Sticky functionality        B2          18          0     ipg160607.xml   9361012                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05
39   9792013                 13            7663607    2010-02-01    Hotelling et al.  cited by applicant   9792013     utility  2017-10-17              Interface scanning for disabled users        B2          24          0     ipg171017.xml   9792013                  0  3e5cae88-ed9d-4912-8c9d-de81d98a05f6                                    None                                   None                           Apple Inc.            2.0  c6a61746-16c7-11ed-9b5f-1234bde3cd05